language: clojure
#lein: lein
script:
  - lein sub install
  - lein sub test
#notifications:
#  irc: "irc.freenode.org#clj-postgresql"
services:
  - postgresql
addons:
  postgresql: "10"
before_script:
  - psql -U postgres -c 'CREATE DATABASE clj_pg_test;' postgres
  - psql -U postgres -c 'CREATE EXTENSION postgis;' clj_pg_test
after_failure:
  - psql -c '\d' -U postgres
  - cat /var/log/postgresql/postgresql-10-main.log
env: PGDATABASE='clj_pg_test' PGUSER='postgres'
#virt: lxd
#os: linux
#dist: focal
#arch: arm64
